/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.BorderLayout;
import java.util.logging.Level;
import java.util.logging.Logger;
import modelos.Modelo;
import weka.gui.treevisualizer.PlaceNode2;
import weka.gui.treevisualizer.TreeVisualizer;

/**
 *
 * @author anlesvavor
 */
public class VistaModelo extends javax.swing.JPanel {

    Modelo modelo;
    public static int contador = 0;
    /**
     * Creates new form VistaModelo
     */
    public VistaModelo() {
        initComponents();
    }

    public VistaModelo(Modelo modelo) {
        initComponents();
        this.modelo = modelo;
        contador++;
        lblNume.setText("" + contador);
        lblNumCondiciones.setText("Número de condiciones simples: " + modelo.getNumeroCondiciones());
        lblPrecision.setText(String.format("Precisión: %10.2f", modelo.getPrecision()));
        lblDML.setText(String.format("Calidad (DML): %10.2f", modelo.getDML()));
        btnMejor.setSelected(modelo.isMejor());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        lblPrecision = new javax.swing.JLabel();
        lblNumCondiciones = new javax.swing.JLabel();
        lblDML = new javax.swing.JLabel();
        btnVerModelo = new javax.swing.JButton();
        btnMejor = new javax.swing.JToggleButton();
        chkSeleccionado = new javax.swing.JCheckBox();
        lblNume = new javax.swing.JLabel();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        lblPrecision.setText("Precisión:");

        lblNumCondiciones.setText("Número de condiciónes simples");

        lblDML.setText("Calidad (DML):");

        btnVerModelo.setText("Ver modelo...");
        btnVerModelo.setToolTipText("Se muestra el árbol de decisión que representa el modelo.");
        btnVerModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerModeloActionPerformed(evt);
            }
        });

        btnMejor.setText("El mejor modelo");
        btnMejor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMejorActionPerformed(evt);
            }
        });

        chkSeleccionado.setText("Seleccionado");
        chkSeleccionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSeleccionadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNume)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPrecision))
                    .addComponent(chkSeleccionado))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                        .addComponent(btnMejor)
                        .addGap(212, 212, 212)
                        .addComponent(btnVerModelo)
                        .addGap(51, 51, 51))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(lblNumCondiciones)
                        .addGap(117, 117, 117)
                        .addComponent(lblDML)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecision)
                    .addComponent(lblNumCondiciones)
                    .addComponent(lblDML)
                    .addComponent(lblNume))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerModelo)
                    .addComponent(btnMejor)
                    .addComponent(chkSeleccionado))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerModeloActionPerformed
        TreeVisualizer tv = null;
        try {
            // display classifier
            final javax.swing.JFrame jf
                    = new javax.swing.JFrame("Weka Classifier Tree Visualizer: J48");
            jf.setSize(500, 400);
            jf.getContentPane().setLayout(new BorderLayout());
            tv = new TreeVisualizer(null,
                    modelo.getModelo().graph(),
                    new PlaceNode2());
            jf.getContentPane().add(tv, BorderLayout.CENTER);
            jf.addWindowListener(new java.awt.event.WindowAdapter() {
                public void windowClosing(java.awt.event.WindowEvent e) {
                    jf.dispose();
                }
            }); 
            jf.setVisible(true);
            jf.setLocation(null);
            tv.fitToScreen();
        } catch (Exception ex) {
            Logger.getLogger(VistaModelo.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
        }
    }//GEN-LAST:event_btnVerModeloActionPerformed

    private void chkSeleccionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSeleccionadoActionPerformed
        modelo.setSeleccionado(chkSeleccionado.isSelected());
    }//GEN-LAST:event_chkSeleccionadoActionPerformed

    private void btnMejorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMejorActionPerformed
        VistaModelos vista = (VistaModelos) getParent();
        vista.cambiarMejor(modelo);
    }//GEN-LAST:event_btnMejorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnMejor;
    private javax.swing.JButton btnVerModelo;
    private javax.swing.JCheckBox chkSeleccionado;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel lblDML;
    private javax.swing.JLabel lblNumCondiciones;
    private javax.swing.JLabel lblNume;
    private javax.swing.JLabel lblPrecision;
    // End of variables declaration//GEN-END:variables

}
